#!/bin/bash

cd ~/.config/chromium/Default
for i in `file *|grep SQL|cut -f1 -d:`; do echo "VACUUM;" | sqlite3 $i ; echo $i Ok; done
cd *Storage && for i in `file *|grep SQL|cut -f1 -d:`; do echo "VACUUM;" | sqlite3 $i ; echo $i Ok; done
cd ~
